import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../public/css/globals.css";
import localFont from "next/font/local";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const urbanistItalic = localFont({
    src: "../public/fonts/Urbanist-Italic-VariableFont_wght.ttf",
    variable: "--font-urbanist-italic",
});

const unbanist = localFont({
    src: "../public/fonts/Urbanist-VariableFont_wght.ttf",
    variable: "--font-urbanist",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {

return (
    <html lang="en">
        <body
            className={`
                ${geistSans.variable}
                ${geistMono.variable}
                ${urbanistItalic.variable}
                ${unbanist.variable}
                antialiased
                bg-background
            `}
        >
            {children}
        </body>
    </html>
);
}

export default RootLayout;