import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import DateTimeProvider from "@/constant/datetime-provider";
import QueryProvider from "@/constant/query-provider";

const urbanistItalic = localFont({
    src: "../public/fonts/Urbanist-Italic-VariableFont_wght.ttf",
    variable: "--font-urbanist-italic",
});

const unbanist = localFont({
    src: "../public/fonts/Urbanist-VariableFont_wght.ttf",
    variable: "--font-urbanist",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = ({
    children
}: Readonly<{
    children: React.ReactNode;
}>) => {

return (
    <html lang="en">
        <body
            className={`
                ${urbanistItalic.variable}
                ${unbanist.variable}
                antialiased
            `}
        >
            <QueryProvider>
                <DateTimeProvider>
                    {children}
                </DateTimeProvider>
            </QueryProvider>
        </body>
    </html>
);
}

export default RootLayout;